config:
    send_anonymous_usage_stats: True
    use_colors: True

my_profile:
 outputs:
   prod:
     type: postgres
     threads: 1
     host: localhost
     port: 5432
     user: user1
     pass: user1
     dbname: test_db
     schema: prod1
   target: prod
